import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Link } from "@tanstack/react-router";
import { CheckSquare, Download, Loader2, Square, Target } from "lucide-react";
import { motion } from "motion/react";
import { useState } from "react";
import { toast } from "sonner";
import type { Career } from "../backend.d";
import { CategoryBadge } from "../components/CategoryBadge";
import {
  useGetAllCareers,
  useGetLatestAssessment,
  useGetMilestones,
  useToggleMilestone,
} from "../hooks/useQueries";

function MilestoneTracker({ career }: { career: Career }) {
  const { data: milestones, isLoading } = useGetMilestones(career.title);
  const toggleMilestone = useToggleMilestone();

  const handleToggle = async (year: bigint, taskText: string) => {
    try {
      await toggleMilestone.mutateAsync({
        careerTitle: career.title,
        year,
        taskText,
      });
    } catch {
      toast.error("Failed to update milestone");
    }
  };

  const total = milestones?.length ?? 0;
  const completed = milestones?.filter((m) => m.completed).length ?? 0;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  // Group milestones by year
  const byYear = (milestones ?? []).reduce<Record<string, typeof milestones>>(
    (acc, m) => {
      const key = m.year.toString();
      if (!acc[key]) acc[key] = [];
      acc[key]!.push(m);
      return acc;
    },
    {},
  );

  const downloadPDF = () => {
    try {
      // Build a text-based roadmap document and download as .txt
      const lines: string[] = [
        "================================================",
        "  CareerNavigator — Career Roadmap",
        "================================================",
        "",
        `Career: ${career.title}`,
        `Category: ${career.category}`,
        `Progress: ${completed}/${total} milestones completed (${pct}%)`,
        `Generated: ${new Date().toLocaleDateString("en-IN")}`,
        "",
        "--- SALARY RANGE ---",
        `  Entry Level:  ${career.salaryEntry}`,
        `  Mid Level:    ${career.salaryMid}`,
        `  Senior Level: ${career.salarySenior}`,
        "",
      ];

      for (const [yr, tasks] of Object.entries(byYear)) {
        lines.push(`--- YEAR ${yr} ---`);
        for (const task of tasks ?? []) {
          const check = task.completed ? "[✓]" : "[ ]";
          lines.push(`  ${check} ${task.taskText}`);
        }
        lines.push("");
      }

      lines.push("------------------------------------------------");
      lines.push("Generated by CareerNavigator · caffeine.ai");

      const content = lines.join("\n");
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${career.title.replace(/\s+/g, "-")}-roadmap.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success("Roadmap downloaded successfully!");
    } catch {
      toast.error("Failed to download roadmap. Please try again.");
    }
  };

  if (isLoading)
    return (
      <div className="space-y-3">
        {["1", "2", "3", "4"].map((k) => (
          <Skeleton key={k} className="h-16" />
        ))}
      </div>
    );

  if (!milestones || milestones.length === 0) {
    return (
      <Card className="py-8 text-center">
        <CardContent className="space-y-3">
          <Target className="w-10 h-10 text-muted-foreground mx-auto" />
          <p className="font-display font-bold text-sm">No milestones yet</p>
          <p className="text-xs text-muted-foreground">
            Go to the career details page and click "Start My Roadmap" to begin
            tracking.
          </p>
          <Button asChild variant="outline" size="sm">
            <Link to="/careers/$id" params={{ id: career.id.toString() }}>
              View Career Details
            </Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Progress */}
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm font-ui font-medium text-muted-foreground">
            Overall Progress
          </p>
          <p className="text-2xl font-display font-black text-primary">
            {pct}%
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm font-ui text-muted-foreground">
            {completed} of {total} tasks
          </p>
          <Button
            onClick={downloadPDF}
            variant="outline"
            size="sm"
            className="mt-1"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" />
            Download Roadmap
          </Button>
        </div>
      </div>

      <div className="w-full h-3 bg-muted rounded-full overflow-hidden">
        <motion.div
          className="h-full bg-primary rounded-full"
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.8, ease: "easeOut" }}
        />
      </div>

      {/* Milestones by year */}
      {Object.entries(byYear)
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([yr, tasks]) => {
          const yearCompleted = tasks?.filter((t) => t.completed).length ?? 0;
          const yearTotal = tasks?.length ?? 0;
          const yearPct =
            yearTotal > 0 ? Math.round((yearCompleted / yearTotal) * 100) : 0;

          return (
            <Card key={yr}>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <h3 className="font-display font-bold">Year {yr}</h3>
                  <div className="flex items-center gap-2">
                    <div className="relative w-9 h-9">
                      <svg
                        aria-label="Year progress"
                        className="w-9 h-9 -rotate-90"
                        viewBox="0 0 40 40"
                      >
                        <title>Year progress</title>
                        <circle
                          cx="20"
                          cy="20"
                          r="16"
                          fill="none"
                          strokeWidth="4"
                          className="stroke-muted"
                        />
                        <motion.circle
                          cx="20"
                          cy="20"
                          r="16"
                          fill="none"
                          strokeWidth="4"
                          strokeLinecap="round"
                          className="stroke-primary"
                          strokeDasharray={`${2 * Math.PI * 16}`}
                          animate={{
                            strokeDashoffset:
                              2 * Math.PI * 16 * (1 - yearPct / 100),
                          }}
                          transition={{ duration: 0.6 }}
                        />
                      </svg>
                      <span className="absolute inset-0 flex items-center justify-center text-[9px] font-bold">
                        {yearPct}%
                      </span>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-2">
                {tasks?.map((m, i) => (
                  <motion.div
                    key={m.taskText}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: i * 0.05 }}
                    className={`flex items-start gap-3 p-3 rounded-xl cursor-pointer transition-all hover:bg-accent group ${
                      m.completed ? "opacity-70" : ""
                    }`}
                    onClick={() => handleToggle(m.year, m.taskText)}
                  >
                    {m.completed ? (
                      <CheckSquare className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
                    ) : (
                      <Square className="w-4 h-4 text-muted-foreground mt-0.5 flex-shrink-0 group-hover:text-primary transition-colors" />
                    )}
                    <span
                      className={`text-sm font-ui ${m.completed ? "line-through text-muted-foreground" : "text-foreground"}`}
                    >
                      {m.taskText}
                    </span>
                  </motion.div>
                ))}
              </CardContent>
            </Card>
          );
        })}
    </div>
  );
}

export function MilestonesPage() {
  const { data: assessment } = useGetLatestAssessment();
  const { data: careers, isLoading } = useGetAllCareers();

  const trackedCareers: Career[] = assessment
    ? (careers ?? [])
        .filter((c) => assessment.topCareers.includes(c.id))
        .slice(0, 3)
    : (careers ?? []).slice(0, 1);

  const [selectedCareer, setSelectedCareer] = useState<Career | null>(null);
  const activeCareer = selectedCareer ?? trackedCareers[0] ?? null;

  return (
    <div className="min-h-screen py-8">
      <div className="container mx-auto px-4 max-w-3xl space-y-8">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-display font-black mb-2">
            Milestone Tracker
          </h1>
          <p className="text-muted-foreground font-ui text-sm">
            Track your year-by-year progress toward your career goals
          </p>
        </div>

        {isLoading ? (
          <div className="space-y-4">
            {["1", "2", "3"].map((k) => (
              <Skeleton key={k} className="h-20" />
            ))}
          </div>
        ) : trackedCareers.length === 0 ? (
          <Card className="py-12 text-center">
            <CardContent className="space-y-4">
              <Target className="w-12 h-12 text-muted-foreground mx-auto" />
              <p className="font-display font-bold">
                No career roadmaps started
              </p>
              <p className="text-sm text-muted-foreground">
                Take an assessment or explore careers to start tracking
                milestones.
              </p>
              <div className="flex gap-3 justify-center">
                <Button asChild variant="outline">
                  <Link to="/assessment">Take Assessment</Link>
                </Button>
                <Button asChild>
                  <Link to="/careers">Explore Careers</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : (
          <>
            {/* Career selector */}
            {trackedCareers.length > 1 && (
              <div className="flex flex-wrap gap-2">
                {trackedCareers.map((career) => (
                  <button
                    type="button"
                    key={career.id.toString()}
                    onClick={() => setSelectedCareer(career)}
                    className={`flex items-center gap-2 px-4 py-2 rounded-full border text-sm font-ui font-medium transition-all ${
                      activeCareer?.id === career.id
                        ? "bg-primary text-primary-foreground border-primary"
                        : "bg-card text-muted-foreground border-border hover:border-primary/40"
                    }`}
                  >
                    {career.title}
                    <CategoryBadge
                      category={career.category}
                      className="scale-90"
                    />
                  </button>
                ))}
              </div>
            )}

            {/* Active career header */}
            {activeCareer && (
              <div className="flex items-center justify-between">
                <div>
                  <CategoryBadge
                    category={activeCareer.category}
                    className="mb-1.5"
                  />
                  <h2 className="text-xl font-display font-black">
                    {activeCareer.title}
                  </h2>
                </div>
                <Button asChild variant="outline" size="sm">
                  <Link
                    to="/careers/$id"
                    params={{ id: activeCareer.id.toString() }}
                  >
                    Career Details
                  </Link>
                </Button>
              </div>
            )}

            {/* Milestone content */}
            {activeCareer && <MilestoneTracker career={activeCareer} />}
          </>
        )}
      </div>
    </div>
  );
}
