/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Skill = IDL.Record({
  'requiredLevel' : IDL.Nat,
  'skillName' : IDL.Text,
});
export const RoadmapYear = IDL.Record({
  'tasks' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
});
export const Career = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salarySenior' : IDL.Text,
  'educationPath' : IDL.Vec(IDL.Text),
  'salaryEntry' : IDL.Text,
  'description' : IDL.Text,
  'topCompanies' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'salaryMid' : IDL.Text,
  'requiredSkills' : IDL.Vec(Skill),
  'roadmapYears' : IDL.Vec(RoadmapYear),
});
export const StudyMaterial = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'materialType' : IDL.Text,
});
export const SkillRating = IDL.Record({
  'skillName' : IDL.Text,
  'userRating' : IDL.Nat,
});
export const Assessment = IDL.Record({
  'governmentScore' : IDL.Nat,
  'topCareers' : IDL.Vec(IDL.Nat),
  'businessScore' : IDL.Nat,
  'skillRatings' : IDL.Vec(SkillRating),
  'medicalScore' : IDL.Nat,
  'creativeScore' : IDL.Nat,
  'timestamp' : IDL.Int,
  'technicalScore' : IDL.Nat,
  'researchScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'stream' : IDL.Text,
  'name' : IDL.Text,
  'education' : IDL.Text,
});
export const Milestone = IDL.Record({
  'completed' : IDL.Bool,
  'year' : IDL.Nat,
  'taskText' : IDL.Text,
  'careerTitle' : IDL.Text,
});
export const QuestionAttempt = IDL.Record({
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const Question = IDL.Record({
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Reminder = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReminder' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'careerChat' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'deleteReminder' : IDL.Func([IDL.Text], [], []),
  'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
  'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerById' : IDL.Func([IDL.Nat], [IDL.Opt(Career)], ['query']),
  'getCareersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Career)], ['query']),
  'getLatestAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
  'getMilestones' : IDL.Func([IDL.Text], [IDL.Vec(Milestone)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getQuestionHistory' : IDL.Func([], [IDL.Vec(QuestionAttempt)], ['query']),
  'getRandomQuestions' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getStudyMaterials' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initMilestones' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAssessment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(SkillRating),
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveQuestionAttempt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'toggleMilestone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'toggleReminderComplete' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Skill = IDL.Record({
    'requiredLevel' : IDL.Nat,
    'skillName' : IDL.Text,
  });
  const RoadmapYear = IDL.Record({
    'tasks' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
  });
  const Career = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salarySenior' : IDL.Text,
    'educationPath' : IDL.Vec(IDL.Text),
    'salaryEntry' : IDL.Text,
    'description' : IDL.Text,
    'topCompanies' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'salaryMid' : IDL.Text,
    'requiredSkills' : IDL.Vec(Skill),
    'roadmapYears' : IDL.Vec(RoadmapYear),
  });
  const StudyMaterial = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'materialType' : IDL.Text,
  });
  const SkillRating = IDL.Record({
    'skillName' : IDL.Text,
    'userRating' : IDL.Nat,
  });
  const Assessment = IDL.Record({
    'governmentScore' : IDL.Nat,
    'topCareers' : IDL.Vec(IDL.Nat),
    'businessScore' : IDL.Nat,
    'skillRatings' : IDL.Vec(SkillRating),
    'medicalScore' : IDL.Nat,
    'creativeScore' : IDL.Nat,
    'timestamp' : IDL.Int,
    'technicalScore' : IDL.Nat,
    'researchScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'stream' : IDL.Text,
    'name' : IDL.Text,
    'education' : IDL.Text,
  });
  const Milestone = IDL.Record({
    'completed' : IDL.Bool,
    'year' : IDL.Nat,
    'taskText' : IDL.Text,
    'careerTitle' : IDL.Text,
  });
  const QuestionAttempt = IDL.Record({
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const Question = IDL.Record({
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Reminder = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReminder' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'careerChat' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'deleteReminder' : IDL.Func([IDL.Text], [], []),
    'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
    'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerById' : IDL.Func([IDL.Nat], [IDL.Opt(Career)], ['query']),
    'getCareersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Career)], ['query']),
    'getLatestAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
    'getMilestones' : IDL.Func([IDL.Text], [IDL.Vec(Milestone)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getQuestionHistory' : IDL.Func([], [IDL.Vec(QuestionAttempt)], ['query']),
    'getRandomQuestions' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getStudyMaterials' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initMilestones' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAssessment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(SkillRating),
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveQuestionAttempt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'toggleMilestone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'toggleReminderComplete' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };