/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'governmentScore' : bigint,
  'topCareers' : Array<bigint>,
  'businessScore' : bigint,
  'skillRatings' : Array<SkillRating>,
  'medicalScore' : bigint,
  'creativeScore' : bigint,
  'timestamp' : bigint,
  'technicalScore' : bigint,
  'researchScore' : bigint,
}
export interface Career {
  'id' : bigint,
  'title' : string,
  'salarySenior' : string,
  'educationPath' : Array<string>,
  'salaryEntry' : string,
  'description' : string,
  'topCompanies' : Array<string>,
  'category' : string,
  'salaryMid' : string,
  'requiredSkills' : Array<Skill>,
  'roadmapYears' : Array<RoadmapYear>,
}
export interface Milestone {
  'completed' : boolean,
  'year' : bigint,
  'taskText' : string,
  'careerTitle' : string,
}
export interface Question {
  'correctIndex' : bigint,
  'explanation' : string,
  'text' : string,
  'options' : Array<string>,
}
export interface QuestionAttempt {
  'total' : bigint,
  'score' : bigint,
  'timestamp' : bigint,
  'category' : string,
}
export interface Reminder {
  'title' : string,
  'completed' : boolean,
  'dueDate' : bigint,
  'description' : string,
}
export interface RoadmapYear { 'tasks' : Array<string>, 'year' : bigint }
export interface Skill { 'requiredLevel' : bigint, 'skillName' : string }
export interface SkillRating { 'skillName' : string, 'userRating' : bigint }
export interface StudyMaterial {
  'url' : string,
  'title' : string,
  'difficulty' : string,
  'description' : string,
  'materialType' : string,
}
export interface UserProfile {
  'stream' : string,
  'name' : string,
  'education' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReminder' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'careerChat' : ActorMethod<[string], string>,
  'deleteReminder' : ActorMethod<[string], undefined>,
  'getAllCareers' : ActorMethod<[], Array<Career>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getAssessments' : ActorMethod<[], Array<Assessment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerById' : ActorMethod<[bigint], [] | [Career]>,
  'getCareersByCategory' : ActorMethod<[string], Array<Career>>,
  'getLatestAssessment' : ActorMethod<[], [] | [Assessment]>,
  'getMilestones' : ActorMethod<[string], Array<Milestone>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getQuestionHistory' : ActorMethod<[], Array<QuestionAttempt>>,
  'getRandomQuestions' : ActorMethod<[string, bigint], Array<Question>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getStudyMaterials' : ActorMethod<[string], Array<StudyMaterial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initMilestones' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAssessment' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<SkillRating>,
      Array<bigint>,
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[string, string, string], undefined>,
  'saveQuestionAttempt' : ActorMethod<[string, bigint, bigint], undefined>,
  'toggleMilestone' : ActorMethod<[string, bigint, string], undefined>,
  'toggleReminderComplete' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];